/** Report generator — produces Markdown, JSON, and plain text reports */

import * as path from 'path';
import { ReviewSummary, ReviewResult, IssueSeverity } from './issueTypes.js';

export class ReportGenerator {
    /** Generate Markdown report */
    generateMarkdown(summary: ReviewSummary): string {
        const lines: string[] = [];
        lines.push('# Code Review Report');
        lines.push('');
        lines.push(`**Project:** ${summary.projectName}`);
        lines.push(`**Date:** ${summary.date.toISOString()}`);
        lines.push(`**Scanned Files:** ${summary.scannedFiles.length}`);
        lines.push(`**Total Issues:** ${summary.totalIssues}`);
        lines.push(`**Duration:** ${summary.duration}ms`);
        lines.push('');

        // Severity breakdown
        lines.push('## Severity Breakdown');
        lines.push('');
        lines.push('| Severity | Count |');
        lines.push('|----------|-------|');
        for (const sev of [IssueSeverity.Critical, IssueSeverity.High, IssueSeverity.Medium, IssueSeverity.Low]) {
            const count = summary.severityBreakdown[sev] || 0;
            lines.push(`| ${sev} | ${count} |`);
        }
        lines.push('');

        // Category breakdown
        lines.push('## Category Breakdown');
        lines.push('');
        lines.push('| Category | Count |');
        lines.push('|----------|-------|');
        const sortedCategories = Object.entries(summary.categoryBreakdown)
            .sort(([, a], [, b]) => b - a);
        for (const [cat, count] of sortedCategories) {
            lines.push(`| ${cat} | ${count} |`);
        }
        lines.push('');

        // File results
        lines.push('## Detailed Findings');
        lines.push('');

        for (const result of summary.results) {
            if (result.issues.length === 0) { continue; }
            const relPath = this.relativePath(result.file, summary.projectName);
            lines.push(`### File: ${relPath}`);
            lines.push('');
            lines.push(`Language: ${result.language} | Issues: ${result.issues.length} | Scanned: ${result.scannedAt.toISOString()}`);
            lines.push('');

            for (const issue of result.issues) {
                lines.push(`---`);
                lines.push('');
                lines.push(`**Line ${issue.line}**`);
                lines.push(`**Severity:** ${issue.severity}`);
                lines.push(`**Category:** ${issue.category}`);
                lines.push(`**Issue:** ${issue.message}`);
                lines.push(`**Explanation:** ${issue.explanation}`);
                lines.push(`**Suggested Fix:** ${issue.suggestedFix}`);
                lines.push(`**Confidence:** ${Math.round(issue.confidence * 100)}%`);
                if (issue.ruleId) {
                    lines.push(`**Rule:** ${issue.ruleId}`);
                }
                lines.push('');
            }
        }

        // Scanned files list
        lines.push('## Scanned Files');
        lines.push('');
        for (const f of summary.scannedFiles) {
            lines.push(`- ${this.relativePath(f, summary.projectName)}`);
        }
        lines.push('');
        lines.push('---');
        lines.push('*Generated by Universal AI Code Reviewer*');

        return lines.join('\n');
    }

    /** Generate JSON report */
    generateJson(summary: ReviewSummary): string {
        const output = {
            projectName: summary.projectName,
            date: summary.date.toISOString(),
            scannedFiles: summary.scannedFiles.length,
            totalIssues: summary.totalIssues,
            duration: summary.duration,
            severityBreakdown: summary.severityBreakdown,
            categoryBreakdown: summary.categoryBreakdown,
            results: summary.results.map(r => ({
                file: r.file,
                language: r.language,
                scannedAt: r.scannedAt.toISOString(),
                duration: r.duration,
                issues: r.issues.map(i => ({
                    line: i.line,
                    endLine: i.endLine,
                    severity: i.severity,
                    category: i.category,
                    message: i.message,
                    explanation: i.explanation,
                    suggestedFix: i.suggestedFix,
                    confidence: i.confidence,
                    ruleId: i.ruleId
                }))
            }))
        };
        return JSON.stringify(output, null, 2);
    }

    /** Generate plain text report */
    generateText(summary: ReviewSummary): string {
        const lines: string[] = [];
        lines.push('='.repeat(60));
        lines.push('CODE REVIEW REPORT');
        lines.push('='.repeat(60));
        lines.push('');
        lines.push(`Project:       ${summary.projectName}`);
        lines.push(`Date:          ${summary.date.toISOString()}`);
        lines.push(`Scanned Files: ${summary.scannedFiles.length}`);
        lines.push(`Total Issues:  ${summary.totalIssues}`);
        lines.push(`Duration:      ${summary.duration}ms`);
        lines.push('');

        lines.push('-'.repeat(40));
        lines.push('SEVERITY BREAKDOWN');
        lines.push('-'.repeat(40));
        for (const sev of [IssueSeverity.Critical, IssueSeverity.High, IssueSeverity.Medium, IssueSeverity.Low]) {
            const count = summary.severityBreakdown[sev] || 0;
            lines.push(`  ${sev.padEnd(10)} ${count}`);
        }
        lines.push('');

        for (const result of summary.results) {
            if (result.issues.length === 0) { continue; }
            const relPath = this.relativePath(result.file, summary.projectName);
            lines.push('-'.repeat(40));
            lines.push(`FILE: ${relPath}`);
            lines.push(`Language: ${result.language} | Issues: ${result.issues.length}`);
            lines.push('-'.repeat(40));

            for (const issue of result.issues) {
                lines.push('');
                lines.push(`  Line ${issue.line}`);
                lines.push(`  Severity: ${issue.severity}`);
                lines.push(`  Issue: ${issue.message}`);
                lines.push(`  Explanation: ${issue.explanation}`);
                lines.push(`  Suggested Fix: ${issue.suggestedFix}`);
            }
            lines.push('');
        }

        lines.push('='.repeat(60));
        lines.push('Generated by Universal AI Code Reviewer');

        return lines.join('\n');
    }

    /** Build a review summary from an array of results */
    buildSummary(projectName: string, results: ReviewResult[], totalDuration: number): ReviewSummary {
        const severityBreakdown: Record<string, number> = {};
        const categoryBreakdown: Record<string, number> = {};
        let totalIssues = 0;

        for (const sev of Object.values(IssueSeverity)) {
            severityBreakdown[sev] = 0;
        }

        for (const result of results) {
            for (const issue of result.issues) {
                totalIssues++;
                severityBreakdown[issue.severity] = (severityBreakdown[issue.severity] || 0) + 1;
                categoryBreakdown[issue.category] = (categoryBreakdown[issue.category] || 0) + 1;
            }
        }

        return {
            projectName,
            date: new Date(),
            scannedFiles: results.map(r => r.file),
            totalIssues,
            severityBreakdown,
            categoryBreakdown,
            results,
            duration: totalDuration
        };
    }

    private relativePath(filePath: string, projectRoot: string): string {
        try {
            return path.relative(projectRoot, filePath).replace(/\\/g, '/');
        } catch {
            return filePath;
        }
    }
}
